apiVersion: v1
kind: ConfigMap
metadata:
  name: kafka-ui-config
  namespace: farmkart-kafka
  labels:
    app.kubernetes.io/name: kafka-ui
    app.kubernetes.io/part-of: farmkart
data:
  dynamic_config.yaml: |
    auth:
      type: LOGIN_FORM
    kafka:
      clusters:
        - name: farmkart-prod
          bootstrapServers: ${KAFKA_BOOTSTRAP_SERVERS}
          readOnly: true
          properties:
            security.protocol: SASL_SSL
            sasl.mechanism: SCRAM-SHA-512
            sasl.jaas.config: org.apache.kafka.common.security.scram.ScramLoginModule required username="${KAFKA_SASL_USERNAME}" password="${KAFKA_SASL_PASSWORD}";
