server:
  port: 8089
  servlet:
    context-path: /reporting-service

spring:
  application:
    name: reporting-service
  datasource:
    url: ${REPORTING_DB_URL:jdbc:mysql://localhost:3306/farmkart_reporting?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true}
    username: ${REPORTING_DB_USER:farmkart}
    password: ${REPORTING_DB_PASS:farmkart}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
  flyway:
    enabled: true
    baseline-on-migrate: true
    validate-on-migrate: false
    out-of-order: true
    locations: classpath:db/migration/reporting

springdoc:
  api-docs:
    path: /reporting-service/api-docs
  swagger-ui:
    path: /reporting-service/swagger-ui.html
