<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <parent>
        <groupId>com.farmkart</groupId>
        <artifactId>farm-kart-parent</artifactId>
        <version>0.0.1-SNAPSHOT</version>
    </parent>
    <artifactId>farm-kart-reporting</artifactId>
    <packaging>pom</packaging>
    <name>farm-kart-reporting</name>
    <modules>
        <module>farm-kart-reporting-client</module>
        <module>farm-kart-reporting-repository</module>
        <module>farm-kart-reporting-service</module>
        <module>farm-kart-reporting-rest</module>
    </modules>
</project>
