server:
  port: 8086
  servlet:
    context-path: /admin-service

spring:
  application:
    name: admin-service
  datasource:
    url: ${ADMIN_DB_URL:jdbc:mysql://localhost:3306/farmkart_admin?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true}
    username: ${ADMIN_DB_USER:farmkart}
    password: ${ADMIN_DB_PASS:farmkart}
  jpa:
    hibernate:
      ddl-auto: validate
  flyway:
    enabled: true
    baseline-on-migrate: true
    validate-on-migrate: false
    out-of-order: true
    locations: classpath:db/migration/admin
  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:localhost:9092}
    consumer:
      group-id: admin-service
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
